// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIXr2PaX95R2Lhl7IQsGFqfhFWOW1EO0',
    appId: '1:394803219867:web:705995efc870e79811e53e',
    messagingSenderId: '394803219867',
    projectId: 'tracking-38143',
    authDomain: 'tracking-38143.firebaseapp.com',
    storageBucket: 'tracking-38143.appspot.com',
    measurementId: 'G-6DM52FSE30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMizKCEfPUJM6yp-w_rTEwJSNE6rbhSx4',
    appId: '1:394803219867:android:586376c8aa9a1f7b11e53e',
    messagingSenderId: '394803219867',
    projectId: 'tracking-38143',
    storageBucket: 'tracking-38143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGzRdLAwz0Z8HdaMi_rescEtS-W8gK44',
    appId: '1:394803219867:ios:5597e2954b23291811e53e',
    messagingSenderId: '394803219867',
    projectId: 'tracking-38143',
    storageBucket: 'tracking-38143.appspot.com',
    iosClientId: '394803219867-76tlg31p6gtjbvtsrrobga7pqlsda8fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.googletrackingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgGzRdLAwz0Z8HdaMi_rescEtS-W8gK44',
    appId: '1:394803219867:ios:5597e2954b23291811e53e',
    messagingSenderId: '394803219867',
    projectId: 'tracking-38143',
    storageBucket: 'tracking-38143.appspot.com',
    iosClientId: '394803219867-76tlg31p6gtjbvtsrrobga7pqlsda8fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.googletrackingProject',
  );
}
